<a href="https://colab.research.google.com/github/Mariam-Hamoda/Spam-Mail-Prediction/blob/main/Spam_mail_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score

In [6]:
mail_data=pd.read_csv('/content/mail_data.csv')

In [7]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

Data Processing

In [8]:
mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

In [9]:
mail_data['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [12]:
X=mail_data['Message']
Y=mail_data['Category']

In [13]:
#label data
encode=LabelEncoder()

In [14]:
Y=encode.fit_transform(Y)
print(Y)
#0 ham
#1 spam

[0 0 1 ... 0 0 0]

Split data for training and testing

In [20]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=3)

Feature Extraction

In [22]:
words=TfidfVectorizer(min_df=1, stop_words='english',lowercase=True)
X_train_feature=words.fit_transform(X_train)
X_test_feature=words.transform(X_test)
print(X_train)
print(X_train_feature)
print(X_test)
print(X_test_feature)

3075                  Don know. I did't msg him recently.
1787    Do you know why god created gap between your f...
1614                         Thnx dude. u guys out 2nite?
4304                                      Yup i'm free...
3266    44 7732584351, Do you want a New Nokia 3510i c...
                              ...
789     5 Free Top Polyphonic Tones call 087018728737,...
968     What do u want when i come back?.a beautiful n...
1667    Guess who spent all last night phasing in and ...
3321    Eh sorry leh... I din c ur msg. Not sad alread...
1688    Free Top ringtone -sub to weekly ringtone-get ...
Name: Message, Length: 4457, dtype: object
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34775 stored elements and shape (4457, 7431)>
  Coords	Values
  (0, 2329)	0.38783870336935383
  (0, 3811)	0.34780165336891333
  (0, 2224)	0.413103377943378
  (0, 4456)	0.4168658090846482
  (0, 5413)	0.6198254967574347
  (1, 3811)	0.17419952275504033
  (1, 3046)	0.2503712792613518
  (1, 1991)	0.33036995955537024
  (1, 2956)	0.33036995955537024
  (1, 2758)	0.3226407885943799
  (1, 1839)	0.2784903590561455
  (1, 918)	0.22871581159877646
  (1, 2746)	0.3398297002864083
  (1, 2957)	0.3398297002864083
  (1, 3325)	0.31610586766078863
  (1, 3185)	0.29694482957694585
  (1, 4080)	0.18880584110891163
  (2, 6601)	0.6056811524587518
  (2, 2404)	0.45287711070606745
  (2, 3156)	0.4107239318312698
  (2, 407)	0.509272536051008
  (3, 7414)	0.8100020912469564
  (3, 2870)	0.5864269879324768
  (4, 2870)	0.41872147309323743
  (4, 487)	0.2899118421746198
  :	:
  (4454, 2855)	0.47210665083641806
  (4454, 2246)	0.47210665083641806
  (4455, 4456)	0.24920025316220423
  (4455, 3922)	0.31287563163368587
  (4455, 6916)	0.19636985317119715
  (4455, 4715)	0.30714144758811196
  (4455, 3872)	0.3108911491788658
  (4455, 7113)	0.30536590342067704
  (4455, 6091)	0.23103841516927642
  (4455, 6810)	0.29731757715898277
  (4455, 5646)	0.33545678464631296
  (4455, 2469)	0.35441545511837946
  (4455, 2247)	0.37052851863170466
  (4456, 2870)	0.31523196273113385
  (4456, 5778)	0.16243064490100795
  (4456, 334)	0.2220077711654938
  (4456, 6307)	0.2752760476857975
  (4456, 6249)	0.17573831794959716
  (4456, 7150)	0.3677554681447669
  (4456, 7154)	0.24083218452280053
  (4456, 6028)	0.21034888000987115
  (4456, 5569)	0.4619395404299172
  (4456, 6311)	0.30133182431707617
  (4456, 647)	0.30133182431707617
  (4456, 141)	0.292943737785358
2632    URGENT! Your mobile No 077xxx WON a £2,000 Bon...
454     Ok i will tell her to stay out. Yeah its been ...
983     Congrats! 2 mobile 3G Videophones R yours. cal...
1282        Am I the only one who doesn't stalk profiles?
4610                               Y de asking like this.
                              ...
4827                        Haha, just what I was thinkin
5291      Xy trying smth now. U eat already? We havent...
3325    I don wake since. I checked that stuff and saw...
3561    Lol I know! Hey someone did a great inpersonat...
1136                      K do I need a login or anything
Name: Message, Length: 1115, dtype: object
<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 7687 stored elements and shape (1115, 7431)>
  Coords	Values
  (0, 1)	0.2381316303003606
  (0, 9)	0.2852706805264544
  (0, 14)	0.26797874471323896
  (0, 20)	0.30668032384591537
  (0, 306)	0.23975986557206702
  (0, 405)	0.2381316303003606
  (0, 1041)	0.28016206931555726
  (0, 1082)	0.2451068436245027
  (0, 1361)	0.25132445289897426
  (0, 1405)	0.3176863938914351
  (0, 1549)	0.2646498848307188
  (0, 4386)	0.18353336340308998
  (0, 5213)	0.1988547357502182
  (0, 5373)	0.2365698724638063
  (0, 6920)	0.20571591693537986
  (0, 7271)	0.1940327008179069
  (1, 3491)	0.496093956101028
  (1, 4418)	0.3457696891316818
  (1, 4729)	0.22965776503163893
  (1, 6214)	0.3621564482127515
  (1, 6507)	0.26731535902873493
  (1, 6588)	0.3298937975962767
  (1, 6732)	0.42473488678029325
  (1, 7368)	0.29957800964520975
  (2, 201)	0.2824102268489399
  :	:
  (1110, 6591)	0.7327660015422193
  (1111, 2440)	0.4137350055985486
  (1111, 3227)	0.44384935772735523
  (1111, 6033)	0.4714849709283488
  (1111, 6787)	0.40050175714278885
  (1111, 7353)	0.4991205841293424
  (1112, 1109)	0.35334496762883244
  (1112, 1683)	0.4017087436272034
  (1112, 2329)	0.241856898377491
  (1112, 4170)	0.3307835623173863
  (1112, 5056)	0.2559183043595413
  (1112, 5695)	0.3381604952481646
  (1112, 5778)	0.22807428098549426
  (1112, 6297)	0.3056896872268727
  (1112, 6777)	0.32853717524096393
  (1112, 7071)	0.33558524648843113
  (1113, 2224)	0.33379592674353104
  (1113, 2852)	0.5956422931588335
  (1113, 3113)	0.3384083342515567
  (1113, 3281)	0.3323250860171953
  (1113, 3811)	0.2810308058655509
  (1113, 4038)	0.370235205294137
  (1113, 4080)	0.30459473619554067
  (1114, 4033)	0.8543942045002639
  (1114, 4557)	0.5196253874825217

In [27]:
print(Y_train.dtype)

int64

Training the Model

In [28]:
model=LogisticRegression()

In [29]:
model.fit(X_train_feature,Y_train)

LogisticRegression()

Accuracy the training data

In [30]:
train_predict=model.predict(X_train_feature)
train_Accuracy=accuracy_score(Y_train,train_predict)
print(train_Accuracy)

0.9676912721561588

Accuracy the testing data

In [32]:
test_predict=model.predict(X_test_feature)
test_Accuracy=accuracy_score(Y_test,test_predict)
print(test_Accuracy)

0.9668161434977578

Making a Predictive System

In [36]:
input_data = "URGENT! You have won a 1-week FREE membership in our £100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net"
#convert to feature
input_data_feature=words.transform([input_data])
prediction=model.predict(input_data_feature)
print(prediction)

if prediction[0] == 0:
    print('Ham Mail')
else:
    print('Spam Mail')

[1]
Spam Mail

In [39]:
input_data = "HI ! How are u ? I'm Mariam ! I met u last night and u tell me u give me a Prize $100,000!"
input_data_feature=words.transform([input_data])
prediction=model.predict(input_data_feature)
print(prediction)

if prediction[0] == 0:
    print('Ham Mail')
else:
    print('Spam Mail')

[0]
Ham Mail